---
title: "Analyse_Univarié"
output: html_notebook
---
# Installation et import des librairies tidyverse
```{r}
library(devtools)
library(FactoMineR)
library(factoextra)
library(compositions)
library(tidyverse)
library(GGally)
library(stats)
library(ggplot2)
library(tidyr)
library(car)
```

# Lecture du fichier csv
```{r}
data <- read.csv("data/data_abs.csv")
```

# Affichage des dimensions du dataframe
```{r}
dim(data)
```

# Affichage des types de données
```{r}
str(data)
```

# Affichage des statistiques descriptives
```{r}
summary(data)
```

# Histogramme pour chaque variable
```{r}
data_quant <- data %>%
    select(HLM, Salairemoy, Ouvrier, Employe, PI, Cadres, Artisant, Agri, TxPauv, NonDiplome, txcho, txabs)
```



# ACP avec données compositionnelles
```{r}
PCA(data_quant, scale.unit = TRUE, ncp = 5, graph = T)
```

```{r}
data_nocomp <- data %>%
    select(Salairemoy, TxPauv, txcho, txabs)

PCA(data_nocomp, scale.unit = TRUE, ncp = 5, graph = T)
```
# Regression Multiple
```{r}
ggpairs(data_nocomp)
```

## Analyse univarié TxAbs
```{r}
hist(data_nocomp$txabs,
     main="Distribution du taux d'abstention",
     xlab="Taux d'abstention",
     ylab="Fréquence",
     col="blue",
     border="red")
```
## Analyse Khi-deux
```{r}
data_comp <- data %>%
  select(Ouvrier, Employe, PI, Cadres, Artisant, Agri)
```

```{r}
resultat_chi2 <- chisq.test(data_quant)
resultat_chi2_nocomp <- chisq.test(data_nocomp)
resultat_chi2_comp <- chisq.test(data_comp)
```

```{r}
print(resultat_chi2)
print(resultat_chi2_nocomp)
print(resultat_chi2_comp)
```